# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool: LinuxAgents

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: 'opencredentialpublisherpublishingserviceapi'
  dockerfilePath: '$(Build.SourcesDirectory)/OpenCredentialPublisher.PublishingService.Api/Dockerfile'
  tag: '$(Build.BuildId)'
  
stages:
- stage: Build
  variables:
  - group: OpenCredentialPublisher.Api-Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Randa OCP Registry'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(System.DefaultWorkingDirectory)'
        tags: '$(tag)'
        arguments: '--build-arg Nuget_OCPPassword=$(ocp-publisher-docker-build)'
    - task: Docker@2
      displayName: Push OCP API to registry
      inputs:
        containerRegistry: 'Randa OCP Registry'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'
