# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'OpenCredentialPublisher.PublishingService.Functions/*'

pool: default
  
steps:
  - task: NuGetAuthenticate@1
    inputs:
      nuGetServiceConnections: 'GITHUB Randa Solutions Packages'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'OpenCredentialPublisher.PublishingService.Functions/OpenCredentialPublisher.PublishingService.Functions.csproj'
      arguments: '--output publish_output --configuration Release'
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true
  
  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifact: functionapp
  